### ISSUE TITLE
error: 'mutex' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by ryandesign** [litehtml/litehtml#225]
litehtml fails to build in my development environment which is based on gcc 9.1.0:

```
src/string_id.cpp:10:13: error: 'mutex' in namespace 'std' does not name a type
   10 | static std::mutex mutex;
      |             ^~~~~
src/string_id.cpp:4:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
    3 | #include <assert.h>
  +++ |+#include <mutex>
    4 | 
```

The compiler's suggestion to include `<mutex>` makes no sense since `<mutex>` is already included on line 2.

The problem was introduced in 8c7621034f2edadc46a9cf236ddef874953c3939 (@stasoid); prior revisions build fine.

**Comment by tordex** [comment]
What is your environment (OS, distribution)?

**Comment by ryandesign** [comment]
I'm cross-compiling for [classic Mac OS](https://en.wikipedia.org/wiki/Classic_Mac_OS) using [Retro68](https://github.com/autc04/Retro68) (on macOS 12, but that's probably not relevant).

**Comment by stasoid** [comment]
@ryandesign Mutexes are not needed in a cooperative multitasking system, so `_GLIBCXX_HAS_GTHREADS` macro is not defined and class mutex is not visible in Retro68.
You can build with LITEHTML_NO_THREADS defined to avoid mutexes.
